const WORD_PAIRS = [
  // Makanan & Minuman (Food & Drink)
  {c: "Sepeda", u: "Motor"}, {c: "Manis", u: "Pahit"}, {c: "Asin", u: "Gurih"}, {c: "Asem", u: "Pedis"},
  {c: "Buah", u: "Sayur"}, {c: "Kursi", u: "Meja"}, {c: "Lampu", u: "Lilin"}, {c: "Kasur", u: "Sofa"},
  {c: "Bantal", u: "Guling"}, {c: "Nasi", u: "Mie"}, {c: "Ayam", u: "Bebek"}, {c: "Kopi", u: "Teh"},
  {c: "Susu", u: "Sirup"}, {c: "Wortel", u: "Lobak"}, {c: "Apel", u: "Pir"}, {c: "Jeruk", u: "Mangga"},
  {c: "Semangka", u: "Melon"}, {c: "Durian", u: "Nangka"}, {c: "Pisang", u: "Pepaya"}, {c: "Bayam", u: "Kangkung"},
  {c: "Kentang", u: "Ubi"}, {c: "Telur", u: "Tahu"}, {c: "Keju", u: "Mentega"}, {c: "Soto", u: "Bakso"},
  {c: "Sate", u: "Gulai"}, {c: "Rendang", u: "Semur"}, {c: "Donat", u: "Roti"}, {c: "Bolu", u: "Brownies"},
  {c: "Pecel", u: "Gado-gado"}, {c: "Siomay", u: "Batagor"}, {c: "Martabak", u: "Terang Bulan"}, {c: "Kerupuk", u: "Emping"},
  {c: "Sambal", u: "Saos"}, {c: "Es Krim", u: "Gelato"}, {c: "Pizza", u: "Burger"}, {c: "Spageti", u: "Fettuccine"},
  {c: "Cokelat", u: "Permen"}, {c: "Kacang", u: "Kuaci"}, {c: "Madu", u: "Selai"}, {c: "Gula", u: "Garam"},
  {c: "Kecap", u: "Saus"}, {c: "Air", u: "Es"}, {c: "Jus", u: "Sari Buah"}, {c: "Soda", u: "Kola"},
  {c: "Beer", u: "Wine"}, {c: "Bubur", u: "Kolak"}, {c: "Lontong", u: "Ketupat"}, {c: "Opor", u: "Gulai"},
  {c: "Lapis", u: "Legit"}, {c: "Klepon", u: "Onde-onde"}, {c: "Cendol", u: "Dawet"}, {c: "Bala-bala", u: "Bakwan"},
  {c: "Tahu", u: "Tempe"}, {c: "Udang", u: "Cumi"}, {c: "Kepiting", u: "Lobster"}, {c: "Ikan", u: "Daging"},

  // Hewan (Animals)
  {c: "Kelinci", u: "Hamster"}, {c: "Burung", u: "Kelelawar"}, {c: "Katak", u: "Kadal"}, {c: "Kupu-kupu", u: "Capung"},
  {c: "Lebah", u: "Tawon"}, {c: "Ular", u: "Cacing"}, {c: "Kucing", u: "Harimau"}, {c: "Anjing", u: "Serigala"},
  {c: "Gajah", u: "Badak"}, {c: "Monyet", u: "Kera"}, {c: "Sapi", u: "Kerbau"}, {c: "Nyamuk", u: "Lalat"},
  {c: "Laba-laba", u: "Kalajengking"}, {c: "Komodo", u: "Biawak"}, {c: "Pinguin", u: "Kutub"}, {c: "Lumba-lumba", u: "Paus"},
  {c: "Singa", u: "Macan"}, {c: "Jerapah", u: "Zebra"}, {c: "Kuda", u: "Keledai"}, {c: "Domba", u: "Kambing"},
  {c: "Ayam", u: "Burung"}, {c: "Bebek", u: "Angsa"}, {c: "Ikan", u: "Belut"}, {c: "Hiu", u: "Paus"},
  {c: "Cicak", u: "Tokek"}, {c: "Tikus", u: "Curut"}, {c: "Semut", u: "Rayap"}, {c: "Cumi", u: "Gurita"},
  {c: "Penyu", u: "Kura-kura"}, {c: "Landak", u: "Tenggiling"}, {c: "Rusa", u: "Kijang"}, {c: "Beruang", u: "Panda"},

  // Profesi & Orang (People & Professions)
  {c: "Kamus", u: "Ensiklopedia"}, {c: "Sekolah", u: "Kampus"}, {c: "Guru", u: "Dosen"}, {c: "Dokter", u: "Perawat"},
  {c: "Polisi", u: "Tentara"}, {c: "Raja", u: "Presiden"}, {c: "Pilot", u: "Nahkoda"}, {c: "Masinis", u: "Supir"},
  {c: "Arsitek", u: "Sipil"}, {c: "Hakim", u: "Jaksa"}, {c: "Pengacara", u: "Notaris"}, {c: "Kakek", u: "Nenek"},
  {c: "Putra", u: "Putri"}, {c: "Ayah", u: "Ibu"}, {c: "Adik", u: "Kakak"}, {c: "Paman", u: "Bibi"},
  {c: "Teman", u: "Sahabat"}, {c: "Pacar", u: "Tunangan"}, {c: "Bos", u: "Manajer"}, {c: "Karyawan", u: "Buruh"},
  {c: "Artis", u: "Selebriti"}, {c: "Penyanyi", u: "Musisi"}, {c: "Pelukis", u: "Pemahat"}, {c: "Koki", u: "Pelayan"},
  {c: "Petani", u: "Nelayan"}, {c: "Atlet", u: "Pemain"}, {c: "Wasit", u: "Pelatih"}, {c: "Siswa", u: "Mahasiswa"},

  // Alam & Tempat (Nature & Places)
  {c: "Laut", u: "Samudera"}, {c: "Gunung", u: "Bukit"}, {c: "Hutan", u: "Taman"}, {c: "Desa", u: "Kota"},
  {c: "Pantai", u: "Pulau"}, {c: "Sungai", u: "Danau"}, {c: "Langit", u: "Awan"}, {c: "Bintang", u: "Planet"},
  {c: "Matahari", u: "Bulan"}, {c: "Pelangi", u: "Kilat"}, {c: "Hujan", u: "Badai"}, {c: "Petir", u: "Guntur"},
  {c: "Angin", u: "Topan"}, {c: "Batu", u: "Pasir"}, {c: "Tanah", u: "Lumpur"}, {c: "Gua", u: "Lubang"},
  {c: "Sawah", u: "Ladang"}, {c: "Kebun", u: "Rimba"}, {c: "Lembah", u: "Ngarai"}, {c: "Air Terjun", u: "Mata Air"},

  // Rumah & Perabot (Home & Furniture)
  {c: "Pintu", u: "Jendela"}, {c: "Tangga", u: "Lift"}, {c: "Pagar", u: "Tembok"}, {c: "Atap", u: "Langit-langit"},
  {c: "Lantai", u: "Karpet"}, {c: "Dapur", u: "Kamar Mandi"}, {c: "Sapu", u: "Pel"}, {c: "Ember", u: "Gayung"},
  {c: "Sendok", u: "Garpu"}, {c: "Piring", u: "Mangkok"}, {c: "Gelas", u: "Cangkir"}, {c: "Pisau", u: "Gunting"},
  {c: "Kompor", u: "Oven"}, {c: "Lemari", u: "Rak"}, {c: "Cermin", u: "Foto"}, {c: "Sikat Gigi", u: "Pasta Gigi"},
  {c: "Handuk", u: "Sabun"}, {c: "Shampoo", u: "Parfum"}, {c: "Kipas Angin", u: "AC"}, {c: "Kulkas", u: "Freezer"},

  // Teknologi & Elektronik (Tech & Electronics)
  {c: "HP", u: "Tablet"}, {c: "Laptop", u: "Komputer"}, {c: "TV", u: "Monitor"}, {c: "Radio", u: "Speaker"},
  {c: "Kamera", u: "Video"}, {c: "Internet", u: "Wifi"}, {c: "Email", u: "Surat"}, {c: "Instagram", u: "TikTok"},
  {c: "Google", u: "Yahoo"}, {c: "Youtube", u: "Netflix"}, {c: "Keyboard", u: "Mouse"}, {c: "Printer", u: "Scanner"},
  {c: "Baterai", u: "Charger"}, {c: "Kabel", u: "Kawat"}, {c: "Remote", u: "Joystick"}, {c: "Robot", u: "Android"},

  // Pakaian & Mode (Clothing & Fashion)
  {c: "Baju", u: "Kaos"}, {c: "Celana", u: "Rok"}, {c: "Sepatu", u: "Sandal"}, {c: "Topi", u: "Helm"},
  {c: "Kacamata", u: "Lensa"}, {c: "Tas", u: "Dompet"}, {c: "Jam Tangan", u: "Gelang"}, {c: "Kalung", u: "Cincin"},
  {c: "Jas", u: "Jaket"}, {c: "Sweater", u: "Hoodie"}, {c: "Seragam", u: "Batik"}, {c: "Kemeja", u: "Blus"},
  {c: "Sabuk", u: "Ikat Pinggang"}, {c: "Kaos Kaki", u: "Sarung Tangan"}, {c: "Payung", u: "Jas Hujan"}, {c: "Kebaya", u: "Gamis"},

  // Olahraga & Hobi (Sports & Hobbies)
  {c: "Basket", u: "Voli"}, {c: "Sepak Bola", u: "Futsal"}, {c: "Renang", u: "Selam"}, {c: "Lari", u: "Jalan"},
  {c: "Gitar", u: "Piano"}, {c: "Drum", u: "Perkusi"}, {c: "Catur", u: "Kartu"}, {c: "Game", u: "Mainan"},
  {c: "Buku", u: "Novel"}, {c: "Komik", u: "Majalah"}, {c: "Film", u: "Series"}, {c: "Bioskop", u: "Teater"},
  {c: "Melukis", u: "Menggambar"}, {c: "Memasak", u: "Memanggang"}, {c: "Menari", u: "Senam"}, {c: "Mancing", u: "Berburu"},

  // Objek & Benda (Objects)
  {c: "Besi", u: "Baja"}, {c: "Kayu", u: "Bambu"}, {c: "Plastik", u: "Karet"}, {c: "Kaca", u: "Kristal"},
  {c: "Kertas", u: "Karton"}, {c: "Kain", u: "Kapas"}, {c: "Emas", u: "Perak"}, {c: "Berlian", u: "Permata"},
  {c: "Uang", u: "Koin"}, {c: "Dompet", u: "Brankas"}, {c: "Kunci", u: "Gembok"}, {c: "Paku", u: "Baut"},
  {c: "Obeng", u: "Tang"}, {c: "Palu", u: "Kapak"}, {c: "Tali", u: "Benang"}, {c: "Jarum", u: "Peniti"},

  // Sifat & Abstrak (Abstract & Verbs)
  {c: "Cepat", u: "Kilat"}, {c: "Lambat", u: "Pelan"}, {c: "Besar", u: "Luas"}, {c: "Kecil", u: "Sempit"},
  {c: "Tinggi", u: "Panjang"}, {c: "Rendah", u: "Pendek"}, {c: "Berat", u: "Keras"}, {c: "Ringan", u: "Empuk"},
  {c: "Muda", u: "Baru"}, {c: "Tua", u: "Lama"}, {c: "Cerah", u: "Terang"}, {c: "Gelap", u: "Suram"},
  {c: "Berani", u: "Kuat"}, {c: "Takut", u: "Cemas"}, {c: "Senang", u: "Bahagia"}, {c: "Sedih", u: "Duka"},
  {c: "Marah", u: "Kesal"}, {c: "Malu", u: "Sungkan"}, {c: "Pintar", u: "Cerdas"}, {c: "Rajin", u: "Giat"},
  {c: "Kaya", u: "Mewah"}, {c: "Miskin", u: "Sederhana"}, {c: "Bersih", u: "Rapi"}, {c: "Kotor", u: "Jorok"},
  {c: "Harum", u: "Wangi"}, {c: "Bau", u: "Busuk"}, {c: "Mahal", u: "Langka"}, {c: "Murah", u: "Diskon"},

  // Tambahan hingga mendekati 500
  {c: "Stasiun", u: "Terminal"}, {c: "Bandara", u: "Pelabuhan"}, {c: "Tiket", u: "Paspor"}, {c: "Hotel", u: "Villa"},
  {c: "Restoran", u: "Warung"}, {c: "Pasar", u: "Mall"}, {c: "Kantor", u: "Pabrik"}, {c: "Bank", u: "ATM"},
  {c: "Rumah Sakit", u: "Klinik"}, {c: "Apotek", u: "Laboratorium"}, {c: "Masjid", u: "Gereja"}, {c: "Candi", u: "Vihara"},
  {c: "Penjara", u: "Sel"}, {c: "Benteng", u: "Istana"}, {c: "Museum", u: "Galeri"}, {c: "Perpustakaan", u: "Arsip"},
  {c: "Jembatan", u: "Terowongan"}, {c: "Jalan", u: "Gang"}, {c: "Trotoar", u: "Zebra Cross"}, {c: "Parkir", u: "Garasi"},
  {c: "Bensin", u: "Solar"}, {c: "Ban", u: "Roda"}, {c: "Setir", u: "Pedal"}, {c: "Spion", u: "Knalpot"},
  {c: "Sepasang", u: "Dua"}, {c: "Ganjil", u: "Genap"}, {c: "Satu", u: "Pertama"}, {c: "Banyak", u: "Semua"},
  {c: "Kosong", u: "Habis"}, {c: "Penuh", u: "Sesak"}, {c: "Terbuka", u: "Bebas"}, {c: "Tertutup", u: "Rapat"},
  {c: "Hidup", u: "Tumbuh"}, {c: "Mati", u: "Gugur"}, {c: "Lahir", u: "Muncul"}, {c: "Tidur", u: "Istirahat"},
  {c: "Makan", u: "Kunyah"}, {c: "Minum", u: "Teguk"}, {c: "Lari", u: "Lompat"}, {c: "Berdiri", u: "Duduk"},
  {c: "Melihat", u: "Menatap"}, {c: "Mendengar", u: "Menyimak"}, {c: "Mencium", u: "Menghirup"}, {c: "Meraba", u: "Menyentuh"},
  {c: "Berbicara", u: "Ngobrol"}, {c: "Menangis", u: "Merintih"}, {c: "Tertawa", u: "Tersenyum"}, {c: "Berpikir", u: "Merenung"},
  {c: "Menulis", u: "Mencatat"}, {c: "Membaca", u: "Belajar"}, {c: "Bekerja", u: "Lembur"}, {c: "Bermain", u: "Liburan"},
  {c: "Mencuci", u: "Membersihkan"}, {c: "Menyapu", u: "Mengepel"}, {c: "Memotong", u: "Membelah"}, {c: "Menjahit", u: "Menyulam"},
  {c: "Membangun", u: "Memperbaiki"}, {c: "Merusak", u: "Menghancurkan"}, {c: "Membeli", u: "Menjual"}, {c: "Membayar", u: "Menagih"},
  {c: "Memberi", u: "Menolong"}, {c: "Menerima", u: "Mengambil"}, {c: "Menyimpan", u: "Menyembunyikan"}, {c: "Mencari", u: "Menemukan"},
  {c: "Lupa", u: "Ingat"}, {c: "Tahu", u: "Paham"}, {c: "Bisa", u: "Mampu"}, {c: "Mau", u: "Ingin"},
  {c: "Cinta", u: "Sayang"}, {c: "Benci", u: "Dendam"}, {c: "Setuju", u: "Yakin"}, {c: "Ragu", u: "Bingung"},
  {c: "Permisi", u: "Maaf"}, {c: "Terima Kasih", u: "Sama-sama"}, {c: "Halo", u: "Hai"}, {c: "Selamat", u: "Sukses"},
  {c: "Pagi", u: "Siang"}, {c: "Sore", u: "Malam"}, {c: "Fajar", u: "Senja"}, {c: "Hari", u: "Tanggal"},
  {c: "Minggu", u: "Bulan"}, {c: "Tahun", u: "Abad"}, {c: "Musim", u: "Cuaca"}, {c: "Panas", u: "Kemarau"},
  {c: "Dingin", u: "Hujan"}, {c: "Salju", u: "Es"}, {c: "Kabut", u: "Asap"}, {c: "Debu", u: "Kotoran"},
  {c: "Sampah", u: "Limbah"}, {c: "Racun", u: "Bisa"}, {c: "Obat", u: "Vitamin"}, {c: "Sakit", u: "Luka"},
  {c: "Sehat", u: "Segar"}, {c: "Kuat", u: "Tangguh"}, {c: "Lemah", u: "Lesu"}, {c: "Capek", u: "Lelah"},
  {c: "Muda", u: "Remaja"}, {c: "Dewasa", u: "Tua"}, {c: "Bayi", u: "Balita"}, {c: "Anak", u: "Bocah"},
  {c: "Manusia", u: "Orang"}, {c: "Pria", u: "Laki-laki"}, {c: "Wanita", u: "Perempuan"}, {c: "Suami", u: "Istri"},
  {c: "Keluarga", u: "Warga"}, {c: "Masyarakat", u: "Rakyat"}, {c: "Bangsa", u: "Negara"}, {c: "Dunia", u: "Alam Semesta"},
  {c: "Utara", u: "Selatan"}, {c: "Barat", u: "Timur"}, {c: "Kanan", u: "Kiri"}, {c: "Atas", u: "Bawah"},
  {c: "Depan", u: "Belakang"}, {c: "Luar", u: "Dalam"}, {c: "Samping", u: "Tengah"}, {c: "Sudut", u: "Pojok"},
  {c: "Lingkaran", u: "Bulat"}, {c: "Kotak", u: "Persegi"}, {c: "Segitiga", u: "Lancip"}, {c: "Lurus", u: "Datar"},
  {c: "Bengkok", u: "Miring"}, {c: "Tebal", u: "Tipis"}, {c: "Halus", u: "Lembut"}, {c: "Kasar", u: "Tajam"},
  {c: "Basah", u: "Lembab"}, {c: "Kering", u: "Gersang"}, {c: "Warna", u: "Corak"}, {c: "Hitam", u: "Gelap"},
  {c: "Putih", u: "Terang"}, {c: "Merah", u: "Jingga"}, {c: "Kuning", u: "Emas"}, {c: "Hijau", u: "Muda"},
  {c: "Biru", u: "Tua"}, {c: "Ungu", u: "Nila"}, {c: "Abu-abu", u: "Perak"}, {c: "Cokelat", u: "Sawo"},
  {c: "Suara", u: "Bunyi"}, {c: "Nada", u: "Irama"}, {c: "Lagu", u: "Musik"}, {c: "Puisi", u: "Sajak"},
  {c: "Cerita", u: "Dongeng"}, {c: "Mitos", u: "Legenda"}, {c: "Fakta", u: "Nyata"}, {c: "Palsu", u: "Tiruan"},
  {c: "Asli", u: "Murni"}, {c: "Baru", u: "Gres"}, {c: "Bekas", u: "Second"}, {c: "Antik", u: "Kuno"},
  {c: "Modern", u: "Canggih"}, {c: "Tradisional", u: "Klasik"}, {c: "Lokal", u: "Nasional"}, {c: "Internasional", u: "Global"},
  {c: "Umum", u: "Publik"}, {c: "Pribadi", u: "Privat"}, {c: "Rahasia", u: "Misteri"}, {c: "Jelas", u: "Pasti"},
  {c: "Mungkin", u: "Bisa Jadi"}, {c: "Penting", u: "Utama"}, {c: "Biasa", u: "Sederhana"}, {c: "Hebat", u: "Luar Biasa"},
  {c: "Lucu", u: "Konyol"}, {c: "Aneh", u: "Unik"}, {c: "Cantik", u: "Indah"}, {c: "Tampan", u: "Gagah"},
  {c: "Jelek", u: "Buruk"}, {c: "Baik", u: "Ramah"}, {c: "Jahat", u: "Kejam"}, {c: "Sifat", u: "Karakter"},
  {c: "Nama", u: "Judul"}, {c: "Kata", u: "Kalimat"}, {c: "Huruf", u: "Angka"}, {c: "Tanda", u: "Simbol"},
  {c: "Gaya", u: "Model"}, {c: "Bentuk", u: "Rupa"}, {c: "Gambar", u: "Lukisan"}, {c: "Video", u: "Rekaman"},
  {c: "Aksi", u: "Gerak"}, {c: "Diam", u: "Tenang"}, {c: "Cepat", u: "Sigap"}, {c: "Lambat", u: "Alon"},
  {c: "Mudah", u: "Gampang"}, {c: "Sulit", u: "Sukar"}, {c: "Curang", u: "Licik"}, {c: "Jujur", u: "Tulus"},
  {c: "Sabar", u: "Tabah"}, {c: "Marah", u: "Emosi"}, {c: "Tenang", u: "Damai"}, {c: "Ribut", u: "Ramai"},
  {c: "Sepi", u: "Sunyi"}, {c: "Akrab", u: "Dekat"}, {c: "Jauh", u: "Asing"}, {c: "Kenal", u: "Tahu"},
  {c: "Lupa", u: "Alpa"}, {c: "Ingat", u: "Sadar"}, {c: "Mimpi", u: "Khayal"}, {c: "Nyata", u: "Realita"},
  {c: "Benar", u: "Betul"}, {c: "Salah", u: "Keliru"}, {c: "Paham", u: "Mengerti"}, {c: "Bingung", u: "Linglung"},
  {c: "Cerdas", u: "Brilian"}, {c: "Bodoh", u: "Dungu"}, {c: "Rajin", u: "Tekun"}, {c: "Malas", u: "Lalai"},
  {c: "Kuat", u: "Perkasa"}, {c: "Lemah", u: "Layu"}, {c: "Berani", u: "Nekat"}, {c: "Takut", u: "Gemetar"},
  {c: "Sombong", u: "Angkuh"}, {c: "Rendah Hati", u: "Sopan"}, {c: "Kikir", u: "Pelit"}, {c: "Dermawan", u: "Murah Hati"},
  {c: "Hemat", u: "Irit"}, {c: "Boros", u: "Foya-foya"}, {c: "Teratur", u: "Disiplin"}, {c: "Berantakan", u: "Kacau"},
  {c: "Indah", u: "Mempesona"}, {c: "Haru", u: "Iba"}, {c: "Iri", u: "Dengki"}, {c: "Bangga", u: "Puas"},
  {c: "Kecewa", u: "Menyesal"}, {c: "Harap", u: "Doa"}, {c: "Janji", u: "Sumpah"}, {c: "Hadiah", u: "Kado"},
  {c: "Pujian", u: "Hinaan"}, {c: "Tantangan", u: "Ujian"}, {c: "Masalah", u: "Kendala"}, {c: "Solusi", u: "Jalan Keluar"},
  {c: "Kesempatan", u: "Peluang"}, {c: "Nasib", u: "Takdir"}, {c: "Keberuntungan", u: "Hoki"}, {c: "Celaka", u: "Musibah"},
  {c: "Kemenangan", u: "Juara"}, {c: "Kekalahan", u: "Gagal"}, {c: "Awal", u: "Mulai"}, {c: "Akhir", u: "Selesai"},
  {c: "Puncak", u: "Gunung"}, {c: "Dasar", u: "Lantai"}, {c: "Tengah", u: "Pusat"}, {c: "Sisi", u: "Pinggir"},
  {c: "Dalam", u: "Inti"}, {c: "Luar", u: "Kulit"}, {c: "Satu", u: "Eka"}, {c: "Dua", u: "Dwi"},
  {c: "Tiga", u: "Tri"}, {c: "Empat", u: "Catur"}, {c: "Lima", u: "Panca"}, {c: "Sepuluh", u: "Dasar"},
  {c: "Seratus", u: "Ratus"}, {c: "Seribu", u: "Ribu"}, {c: "Juta", u: "Miliar"}, {c: "Nol", u: "Kosong"},
  {c: "Plus", u: "Tambah"}, {c: "Minus", u: "Kurang"}, {c: "Kali", u: "Bagi"}, {c: "Sama Dengan", u: "Hasil"},
  {c: "Persen", u: "Bagian"}, {c: "Derajat", u: "Suhu"}, {c: "Meter", u: "Jarak"}, {c: "Gram", u: "Berat"},
  {c: "Liter", u: "Volume"}, {c: "Detik", u: "Waktu"}, {c: "Menit", u: "Jam"}, {c: "Hari", u: "Minggu"},
  {c: "Bulan", u: "Triwulan"}, {c: "Tahun", u: "Semester"}, {c: "Senin", u: "Selasa"}, {c: "Rabu", u: "Kamis"},
  {c: "Jumat", u: "Sabtu"}, {c: "Januari", u: "Februari"}, {c: "Maret", u: "April"}, {c: "Mei", u: "Juni"},
  {c: "Juli", u: "Agustus"}, {c: "September", u: "Oktober"}, {c: "November", u: "Desember"}, {c: "Ramadan", u: "Lebaran"},
  {c: "Natal", u: "Tahun Baru"}, {c: "Libur", u: "Cuti"}, {c: "Piknik", u: "Wisata"}, {c: "Mudik", u: "Pulang"},
  {c: "Tas", u: "Koper"}, {c: "Paspor", u: "Visa"}, {c: "Peta", u: "Navigasi"}, {c: "Arah", u: "Tujuan"},
  {c: "Utara", u: "Kutub"}, {c: "Selatan", u: "Antartika"}, {c: "Barat", u: "Mentari Terbenam"}, {c: "Timur", u: "Fajar"},
  {c: "Kanan", u: "Sisi Luar"}, {c: "Kiri", u: "Sisi Dalam"}, {c: "Atas", u: "Puncak"}, {c: "Bawah", u: "Lembah"},
  {c: "Depan", u: "Muka"}, {c: "Belakang", u: "Pundak"}, {c: "Luar", u: "Eksterior"}, {c: "Dalam", u: "Interior"},
  {c: "Samping", u: "Lateral"}, {c: "Tengah", u: "Median"}, {c: "Sudut", u: "Vertex"}, {c: "Pojok", u: "Ujung"},
  {c: "Garis", u: "Ruas"}, {c: "Bidang", u: "Permukaan"}, {c: "Ruang", u: "Volume"}, {c: "Titik", u: "Noda"},
  {c: "Bulat", u: "Bundar"}, {c: "Kotak", u: "Kubus"}, {c: "Lonjong", u: "Oval"}, {c: "Pipih", u: "Gepeng"},
  {c: "Besar", u: "Agung"}, {c: "Kecil", u: "Mungil"}, {c: "Tinggi", u: "Jangkung"}, {c: "Rendah", u: "Ceper"},
  {c: "Panjang", u: "Lebar"}, {c: "Pendek", u: "Cincang"}, {c: "Tebal", u: "Padat"}, {c: "Tipis", u: "Halus"},
  {c: "Keras", u: "Solid"}, {c: "Lunak", u: "Lembek"}, {c: "Kaku", u: "Tegang"}, {c: "Lentur", u: "Fleksibel"},
  {c: "Pijar", u: "Binar"}, {c: "Redup", u: "Sayup"}, {c: "Silau", u: "Terang Benderang"}, {c: "Suram", u: "Mendap"},
  {c: "Cepat", u: "Laju"}, {c: "Lambat", u: "Pelan"}, {c: "Deras", u: "Kencang"}, {c: "Tenang", u: "Syu"},
  {c: "Ribut", u: "Gaduh"}, {c: "Sepi", u: "Hening"}, {c: "Suci", u: "Kudus"}, {c: "Haram", u: "Dosa"},
  {c: "Mulia", u: "Luhur"}, {c: "Hina", u: "Nista"}, {c: "Aman", u: "Tentram"}, {c: "Bahaya", u: "Gawat"},
  {c: "Piring", u: "Nampan"}, {c: "Mangkuk", u: "Pinggan"}, {c: "Tekko", u: "Ceret"}, {c: "Botol", u: "Termos"},
  {c: "Kuali", u: "Wajan"}, {c: "Sodet", u: "Sendok Goreng"}, {c: "Talenan", u: "Alas Potong"}, {c: "Parutan", u: "Serutan"},
  {c: "Toples", u: "Wadah"}, {c: "Serbet", u: "Tisu"}, {c: "Spons", u: "Sabut"}, {c: "Sikat", u: "Kawat Pompa"},
  {c: "Lem", u: "Isolasi"}, {c: "Selotip", u: "Lakban"}, {c: "Steples", u: "Klip"}, {c: "Map", u: "Amplop"},
  {c: "Kwitansi", u: "Nota"}, {c: "Faktur", u: "Bon"}, {c: "Stempel", u: "Cap"}, {c: "Tinta", u: "Cat"},
  {c: "Kanvas", u: "Kertas Gambar"}, {c: "Kuas", u: "Palet"}, {c: "Pensil Warna", u: "Krayon"}, {c: "Spidol", u: "Stabilo"},
  {c: "Penggaris", u: "Busur"}, {c: "Jangka", u: "Rautan"}, {c: "Penghapus", u: "Tip-Ex"}, {c: "Coretan", u: "Tulisan"},
  {c: "Angka", u: "Bilangan"}, {c: "Rumus", u: "Teori"}, {c: "Data", u: "Informasi"}, {c: "Laporan", u: "Jurnal"},
  {c: "Skripsi", u: "Tesis"}, {c: "Disertasi", u: "Karya Ilmiah"}, {c: "Pidato", u: "Presentasi"}, {c: "Rapat", u: "Seminar"},
  {c: "Diskusi", u: "Debat"}, {c: "Tanya", u: "Jawab"}, {c: "Kritik", u: "Saran"}, {c: "Pujian", u: "Sanjungan"},
  {c: "Janji", u: "Sumpah"}, {c: "Kesepakatan", u: "Kontrak"}, {c: "Izin", u: "Restu"}, {c: "Larangan", u: "Pantangan"},
  {c: "Hukum", u: "Aturan"}, {c: "Norma", u: "Adat"}, {c: "Budaya", u: "Tradisi"}, {c: "Seni", u: "Budaya"},
  {c: "Sejarah", u: "Hikayat"}, {c: "Cerita Rakyat", u: "Legenda"}, {c: "Fabel", u: "Hikayat"}, {c: "Puisi", u: "Sajak"},
  {c: "Pantun", u: "Gurindam"}, {c: "Lagu", u: "Tembang"}, {c: "Irama", u: "Melodi"}, {c: "Harmoni", u: "Nada"},
  {c: "Suara", u: "Vokal"}, {c: "Musik", u: "Instrumen"}, {c: "Konser", u: "Pertunjukan"}, {c: "Drama", u: "Teater"},
  {c: "Wayang", u: "Ketoprak"}, {c: "Tari", u: "Joget"}, {c: "Panggung", u: "Pentas"}, {c: "Layar", u: "Kelir"},
  {c: "Kamera", u: "Lensa"}, {c: "Film", u: "Sinema"}, {c: "Aktor", u: "Bintang"}, {c: "Sutradara", u: "Produser"},
  {c: "Skenario", u: "Naskah"}, {c: "Plot", u: "Alur"}, {c: "Tokoh", u: "Karakter"}, {c: "Peran", u: "Akting"},
  {c: "Juara", u: "Pemenang"}, {c: "Hadiah", u: "Piala"}, {c: "Medali", u: "Piagam"}, {c: "Skor", u: "Nilai"},
  {c: "Ujian", u: "Tes"}, {c: "Tugas", u: "Pekerjaan"}, {c: "Proyek", u: "Kegiatan"}, {c: "Acara", u: "Event"},
  {c: "Pesta", u: "Perayaan"}, {c: "Hiburan", u: "Rekreasi"}, {c: "Wisata", u: "Liburan"}, {c: "Perjalanan", u: "Tour"},
  {c: "Tiket", u: "Kupon"}, {c: "Karcis", u: "Voucher"}, {c: "Kartu", u: "Member"}, {c: "Poin", u: "Bonus"},
  {c: "Diskon", u: "Potongan"}, {c: "Harga", u: "Biaya"}, {c: "Gratis", u: "Cuma-cuma"}, {c: "Murah", u: "Obral"},
  {c: "Mahal", u: "Eksekutif"}, {c: "Mewah", u: "Eksklusif"}, {c: "Sederhana", u: "Polos"}, {c: "Rapi", u: "Apik"},
  {c: "Bersih", u: "Higienis"}, {c: "Wangi", u: "Harum"}, {c: "Segar", u: "Asli"}, {c: "Alami", u: "Organik"},
  {c: "Sehat", u: "Bugar"}, {c: "Kuat", u: "Kokoh"}, {c: "Tangguh", u: "Awet"}, {c: "Cepat", u: "Kilat"},
  {c: "Lambat", u: "Pelan"}, {c: "Sabar", u: "Tenang"}, {c: "Marah", u: "Ganas"}, {c: "Berani", u: "Nekat"},
  {c: "Takut", u: "Ngeri"}, {c: "Senang", u: "Gembira"}, {c: "Sedih", u: "Lara"}, {c: "Haru", u: "Iba"},
  {c: "Bangga", u: "Puas"}, {c: "Malu", u: "Ragu-ragu"}, {c: "Bingung", u: "Pusing"}, {c: "Pintar", u: "Jenius"},
  {c: "Bodoh", u: "Tolol"}, {c: "Lucu", u: "Gokil"}, {c: "Aneh", u: "Ajaib"}, {c: "Nyata", u: "Konkrit"},
  {c: "Maya", u: "Virtual"}, {c: "Digital", u: "Online"}, {c: "Luring", u: "Offline"}, {c: "Sinyal", u: "Jaringan"},
  {c: "Data", u: "Kuota"}, {c: "Pulsa", u: "Saldo"}, {c: "Token", u: "Voucher"}, {c: "User", u: "Akun"},
  {c: "Password", u: "Sandi"}, {c: "Email", u: "Surat Elektronik"}, {c: "Chat", u: "Pesan"}, {c: "Telepon", u: "Panggilan"},
  {c: "Suara", u: "Audio"}, {c: "Gambar", u: "Visual"}, {c: "Teks", u: "Tulisan"}, {c: "File", u: "Berkas"},
  {c: "Folder", u: "Direktori"}, {c: "Aplikasi", u: "Software"}, {c: "Sistem", u: "Program"}, {c: "Mesin", u: "Alat"},
  {c: "Obeng", u: "Kunci Inggris"}, {c: "Tang", u: "Catut"}, {c: "Gergaji", u: "Gerinda"}, {c: "Bor", u: "Pahat"},
  {c: "Palu", u: "Godam"}, {c: "Kikir", u: "Amplas"}, {c: "Baut", u: "Sekrup"}, {c: "Mur", u: "Ring"},
  {c: "Kabel", u: "Kelistrikan"}, {c: "Lampu", u: "Bohlam"}, {c: "Saklar", u: "Stop Kontak"}, {c: "Baterai", u: "Aki"},
  {c: "Mesin Cuci", u: "Pengering"}, {c: "Setrika", u: "Uap"}, {c: "Vakum", u: "Penyedot Debu"}, {c: "Blender", u: "Mixer"},
  {c: "Microwave", u: "Panggang"}, {c: "Rice Cooker", u: "Magic Com"}, {c: "Dispenser", u: "Pompa Air"}, {c: "Teko", u: "Ceret Elektronik"},
  {c: "Sofa", u: "Kursi Empuk"}, {c: "Meja Makan", u: "Meja Tamu"}, {c: "Lemari Pakaian", u: "Buffet"}, {c: "Gorden", u: "Tirai"},
  {c: "Karpet", u: "Permadani"}, {c: "Bantal", u: "Bolster"}, {c: "Selimut", u: "Bed Cover"}, {c: "Sprei", u: "Sarung Kasur"},
  {c: "Handuk", u: "Keset"}, {c: "Ember", u: "Bak Mandi"}, {c: "Shower", u: "Kran"}, {c: "Toilet", u: "Wastafel"},
  {c: "Sabun Mandi", u: "Shampoo"}, {c: "Odol", u: "Sikat Gigi"}, {c: "Sisir", u: "Cermin"}, {c: "Bedak", u: "Lipstik"},
  {c: "Parfum", u: "Minyak Wangi"}, {c: "Dompet", u: "Tas Tangan"}, {c: "Payung", u: "Mantel"}, {c: "Sandal", u: "Selop"},
  {c: "Kaos", u: "Singlet"}, {c: "Kemeja", u: "Poloshirt"}, {c: "Celana Jeans", u: "Chino"}, {c: "Rok", u: "Dress"},
  {c: "Jas", u: "Tuksedo"}, {c: "Batik", u: "Tenun"}, {c: "Sarung", u: "Samping"}, {c: "Mukena", u: "Peci"},
  {c: "Jilbab", u: "Hijab"}, {c: "Sorban", u: "Syal"}, {c: "Kaos Kaki", u: "Legging"}, {c: "Sabuk", u: "Gesper"},
  {c: "Cincin", u: "Mata Kucing"}, {c: "Kalung", u: "Liontin"}, {c: "Anting", u: "Giwang"}, {c: "Gelang", u: "Arloji"},
  {c: "Kacamata Hitam", u: "Kacamata Minus"}, {c: "Softlens", u: "Kontak Lensa"}, {c: "Masker", u: "Face Shield"}, {c: "Topi", u: "Kupluk"},
  {c: "Buku Tulis", u: "Buku Catatan"}, {c: "Binder", u: "File"}, {c: "Kertas A4", u: "Kertas F4"}, {c: "Karton", u: "Styrofoam"},
  {c: "Lemari Buku", u: "Rak Buku"}, {c: "Meja Belajar", u: "Meja Kantor"}, {c: "Pensil", u: "Pulpen"}, {c: "Tipe-x", u: "Penghapus"},
  {c: "Staples", u: "Paper Clip"}, {c: "Spidol Whiteboard", u: "Spidol Permanen"}, {c: "Papan Tulis", u: "Whiteboard"}, {c: "Layar Proyektor", u: "Infocus"},
  {c: "Dosen", u: "Dekan"}, {c: "Rektor", u: "Ketua Yayasan"}, {c: "Mahasiswa", u: "Pelajar"}, {c: "Alumni", u: "Senior"},
  {c: "Wisuda", u: "Kelulusan"}, {c: "Ijazah", u: "Sertifikat"}, {c: "Beasiswa", u: "Subsidi"}, {c: "Uang Spp", u: "Uang Kuliah"},
  {c: "Kantin", u: "Koperasi"}, {c: "Perpustakaan", u: "Laboratorium"}, {c: "Aula", u: "Stadion"}, {c: "Asrama", u: "Kost"},
  {c: "Satpam", u: "Penjaga"}, {c: "Cleaning Service", u: "Tukang Kebun"}, {c: "Supir", u: "Sopir Pribadi"}, {c: "Ojek", u: "Taxi"},
  {c: "Kereta Api", u: "KRL"}, {c: "Pesawat", u: "Helikopter"}, {c: "Kapal Laut", u: "Feri"}, {c: "Bus", u: "Travel"},
  {c: "Sepeda Motor", u: "Skuter"}, {c: "Mobil Mewah", u: "Sport Car"}, {c: "Truk", u: "Kontainer"}, {c: "Alat Berat", u: "Ekskavator"},
  {c: "Jalan Tol", u: "Flyover"}, {c: "Jembatan Layang", u: "Underpass"}, {c: "Lampu Merah", u: "Rambu Lalu Lintas"}, {c: "Polantas", u: "Dishub"}
];

export default function handler(req, res) {
  res.setHeader("Cache-Control", "no-store, max-age=0");
  res.setHeader("Content-Type", "application/json");

  try {
    const randomIndex = Math.floor(Math.random() * WORD_PAIRS.length);
    const pair = WORD_PAIRS[randomIndex];

    return res.status(200).json({
      civilian: pair.c,
      undercover: pair.u,
      totalPairs: WORD_PAIRS.length
    });
  } catch (err) {
    return res.status(500).json({ error: "Gagal mengambil data" });
  }
}
